name: Secrets Scan (OSS - Windows)

on:
  workflow_dispatch:
  workflow_call:
  # push:
  # pull_request:

jobs:
  gitleaks:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Gitleaks (OSS) via Chocolatey
        shell: powershell
        run: |
          choco install gitleaks -y --no-progress
          # Verifica la versi√≥n instalada
          gitleaks version

      - name: Run Gitleaks scan (no fail on findings)
        shell: powershell
        continue-on-error: true
        run: |
          gitleaks detect --source . --report-path gitleaks-report.json --report-format json --verbose

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: ignore
